### PR TITLE
Feature/screen maximized

### PR DESCRIPTION
**Pull request by FabioGNR**
Maximize window. Fix LevelSelectorState so it uses actual screen size.
Does not yet support resizing, but that is not as important.

### CODE REVIEW

**Comment by notzain** [comment]
Level Editor tiles do not fit inside the screen anymore, they overflow outside the window

**Comment by FabioGNR** [comment]
I can't reproduce this issue:
image
Can you show what's going wrong?

**Comment by notzain** [comment]
image

Also does not happen on my Windows. Problem seems to be my screen resolution (2560x1700). Not sure if this also happens on HiDPI Windows machines.

https://github.com/42IN13SAg/Push-d-Out/blob/f2ecd1787c09e1a90cbe618055090d14d965e3f1/game/states/LevelEditorState.cpp#L17

This line returns my screen size, instead of the game resolution.

**Comment by FabioGNR** [comment]
Found a fix: https://stackoverflow.com/questions/33393528/how-to-get-screen-size-in-sdl
I will implement this later

**Comment by FabioGNR** [comment]
Can you try this new build? I think I get the same results on Windows, but haven't tested with High DPI yet.

**Comment by notzain** [comment]
> Can you try this new build? I think I get the same regular results on Windows, but haven't tested with High DPI yet.

That didn't work. I had a quick look, and it seems we can just reuse the WindowProperties when fetching data. It was an easy fix, so I pushed it to the pr.

**Comment by FabioGNR** [comment]
We can't reuse window properties. The window properties are set by the game but have no meaning when the flag 'maximized' is true. So these properties do not hold the current screen size.

**Comment by notzain** [comment]
What problems would reusing window properties cause? I'm not sure I understand the problem there. I think it makes more sense to return the window resolution (which was defined in window properties), than the physical size of the window on the screen. 

I believe RenderLogicalSize is what we want (fit the rendering to the window), but it does cause anti-aliasing issues that you mentioned. 

I think that these 2 issues are something we need to discuss (later), and is for another PR. I will revert my changes.

**Pull request merged**
